spring.application.name=producto
server.port=8080

spring.datasource.url=jdbc:mysql://kodama.proxy.rlwy.net:28975/railway
spring.datasource.username=root
spring.datasource.password=LpQYQEWCxtggruHSZJaDjHkvZOxRvixQ

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true